### PR TITLE
feat: build for additional architecture aarch64

### PR DESCRIPTION
**Pull request by cz8s**
I run netflow-collector on a raspberry-pi which needs the binary to be compiled for the linux/aarch64 architecture

### CODE REVIEW

**Comment by rkosegi** [comment]
Hi @cz8s, thank you for PR.
There already is build for arm64. is there any issue with that image on raspberry pi?

**Comment by cz8s** [comment]
Hi @rkosegi , I am not sure why, but using ` ghcr.io/rkosegi/netflow-collector:latest` results in this error: `exec /netflow-collector: exec format error`

Building it for aarch64 fixes the problem. I can use `ghcr.io/cz8s/netflow-collector:v0.1` without problems.

Maybe some parts of my setup don't know that aarch64 and arm64 are the same? 
I run kubernetes on armbian on a raspberry clone.

**Comment by rkosegi** [comment]
Hi @cz8s, please don't use `latest` tag, it's remainder of old build, which is no longer updated. I removed it from packages already.

Please try latest version 1.1.0, I'm sure there is arm64 variant:

```shell
skopeo inspect --override-arch arm64 docker://ghcr.io/rkosegi/netflow-collector:v1.1.0
{
    "Name": "ghcr.io/rkosegi/netflow-collector",
    "Digest": "sha256:e6217090ad75f32b07fcb7368781227ce42194005340f817efbcd761eee984dc",
    "RepoTags": [
        "1.0.0",
        "1.0.1",
        "1.0.2",
        "v1.0.3",
        "v1.1.0"
    ],
    "Created": "2024-11-02T12:50:34.330726261Z",
    "DockerVersion": "",
    "Labels": {
        "org.opencontainers.image.created": "2024-11-02T12:46:50.933Z",
        "org.opencontainers.image.description": "Simple Netflow V5 exporter for prometheus",
        "org.opencontainers.image.documentation": "https://github.com/rkosegi/netflow-collector/blob/main/README.md",
        "org.opencontainers.image.licenses": "Apache-2.0",
        "org.opencontainers.image.revision": "129ed2b93e08be78d504790d2cd444388c2325aa",
        "org.opencontainers.image.source": "https://github.com/rkosegi/netflow-collector",
        "org.opencontainers.image.title": "netflow-collector",
        "org.opencontainers.image.url": "https://github.com/rkosegi/netflow-collector",
        "org.opencontainers.image.vendor": "rkosegi",
        "org.opencontainers.image.version": "v1.1.0"
    },
    "Architecture": "arm64",
    "Os": "linux",
...
```

You can find details under `packages` in this [repo](https://github.com/rkosegi/netflow-collector/pkgs/container/netflow-collector) in tab "OS/Arch".

**Comment by cz8s** [comment]
aha! That makes more sense. Thanks for the help. And sorry for the noise. Closing this PR then :)

**Pull request closed without merging**
